GHA: Move from deprecated Ubuntu 18 runner
Jobs don't start on that old image.
So use the "ubuntu-latest" runner and a container as the bzr
import/export scripts don't work on later Ubuntu versions:

brz: ERROR: TypeError: startswith first arg must be str or a tuple of str, not bytes

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/breezy/commands.py", line 1017, in exception_to_return_code
    return the_callable(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/breezy/commands.py", line 1206, in run_bzr
    ret = run(*run_argv)
  File "/usr/lib/python3/dist-packages/breezy/commands.py", line 757, in run_argv_aliases
    return self.run(**all_cmd_args)
  File "/usr/lib/python3/dist-packages/breezy/commands.py", line 782, in run
    return class_run(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/breezy/plugins/fastimport/cmds.py", line 315, in run
    return _run(source, generic_processor.GenericProcessor,
  File "/usr/lib/python3/dist-packages/breezy/plugins/fastimport/cmds.py", line 46, in _run
    return proc.process(p.iter_commands)
  File "/usr/lib/python3/dist-packages/breezy/plugins/fastimport/processors/generic_processor.py", line 277, in process
    super(GenericProcessor, self)._process(command_iter)
  File "/usr/lib/python3/dist-packages/fastimport/processor.py", line 79, in _process
    for cmd in command_iter():
  File "/usr/lib/python3/dist-packages/fastimport/parser.py", line 296, in iter_commands
    elif len(line) == 0 or line.startswith(b'#'):
TypeError: startswith first arg must be str or a tuple of str, not bytes